version: 2
jobs:
  build:
    docker:
      - image: .circleci/python:3.9-rc-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: run high priority tests
          command: |
            . venv/bin/activate
             python3 -m pytest -m high -v  --alluredir ~/repo/raw_test_result_jsons

      - run:
          name: run moderate priority tests
          command: |
            . venv/bin/activate
             python3 -m pytest -m moderate -v  --alluredir ~/repo/raw_test_result_jsons

      - run:
          name: run low priority tests
          command: |
            . venv/bin/activate
             python3 -m pytest -m low -v  --alluredir ~/repo/raw_test_result_jsons

      - run:
          name: install allure CLI
          command: |
            uname -a
            sudo npm install -g allure-commandline --save-dev

      - run:
          name: generate report
          command: |
            allure generate -c ~/repo/raw_test_result_jsons -o ~/repo/test-reports

      - store_artifacts:
          path: test-reports
          destination: test-reports
          when: always